# Generated by Django 6.0.8 on 2026-08-31 08:25

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('network_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkelement',
            name='color',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkelement',
            name='role',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='networkelement',
            name='tags',
        ),
        migrations.CreateModel(
            name='VlanElement',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='networkelement',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
