[project]
name = "network_map"
version = "0.1.0"
requires-python = ">=3.12.0"
authors = [
    { name = "Yannick Wernle", email = "yannick@wernle.net" }
]
description = "A network_map plugin for netbox"
license = "GPL-3.0"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/yativilli/netbox_networkmap_plugin"
Repository = "https://github.com/yativilli/netbox_networkmap_plugin"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["network_map"]
include-package-data = true

[tool.setuptools.package-dir]
network_map = "network_map"

[tool.setuptools.package-data]
network_map = [
    "templates/**",
    "static/**",
    "locale/**/*.mo"
]
