LOCATION_COLORS = (
    ("location-color-0", "#0072b2"),
    ("location-color-1", "#d55e00"),
    ("location-color-2", "#009e73"),
    ("location-color-3", "#cc79a7"),
    ("location-color-4", "#e69f00"),
    ("location-color-5", "#56b4e9"),
    ("location-color-6", "#882255"),
    ("location-color-7", "#117733"),
    ("location-color-8", "#332288"),
    ("location-color-9", "#aa4499"),
    ("location-color-10", "#44aa99"),
    ("location-color-11", "#999933"),
    ("location-color-12", "#661100"),
    ("location-color-13", "#6699cc"),
    ("location-color-14", "#aa4466"),
    ("location-color-15", "#447744"),
    ("location-color-16", "#774488"),
    ("location-color-17", "#cc6677"),
    ("location-color-18", "#117755"),
    ("location-color-19", "#999933"),
)


def color_for_location(index: int) -> str:
    return LOCATION_COLORS[index % len(LOCATION_COLORS)][0]


def color_for_location_hex(index: int) -> str:
    return LOCATION_COLORS[index % len(LOCATION_COLORS)][1]


# Shades of one base colour, generated by mixing it towards white and black.
# The base colour stays index 0, then the sequence alternates lighter and
# darker, which keeps every prefix of a subnet recognisable as one family
# while still giving each prefix its own clearly distinct colour.
SHADE_STEP = 0.18
SHADE_MAX = 0.82


def shade_of(color: str, index: int) -> str:
    """
    Return `color` for index 0, then progressively lighter (odd indexes) and
    darker (even indexes) mixes of it. Only the lightness moves, so the
    prefixes of one subnet read as a colour family on the map, in the floor
    plan and in the SVG exports.
    """
    if not isinstance(color, str) or len(color) != 7 or color[0] != "#":
        return color
    try:
        channels = [int(color[i : i + 2], 16) for i in (1, 3, 5)]
    except ValueError:
        return color
    if index <= 0:
        return color
    factor = min(SHADE_MAX, SHADE_STEP * ((index + 1) // 2))
    target = 255.0 if index % 2 else 0.0
    mixed = [round(channel + (target - channel) * factor) for channel in channels]
    return f"#{mixed[0]:02x}{mixed[1]:02x}{mixed[2]:02x}"
